git:
  commit:
    # auto stage changes while commit
    auto_stage: true
    # template for git commit message
    # value is an array, min length and max length
    message:
      - title:
          comment: 'What did you do in this commit?'
          template: '{}'
          min: 10
          max: 100
      - issue:
          comment: 'Relevant issue?'
          template: 'issue: {}'
  flow:
    branch:
      production: 'master'
      development: 'develop'
    prefix:
      feature: 'feature/'
      release: 'release/'
      hotfix: 'hotfix/'
      version: ''
    release:
      # commit message of release finish, leave it null if you want to input it by yourself
      finish_message: 'gas: release new version'
  tag:
    # tag message of release finish, leave it null if you want to input it by yourself
    tag_message: 'gas automatic tag'

alias:
  - ll:
      description: 'git log graph pretty'
      cmd: 'git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset%n" --abbrev-commit --date=relative --branches'
